import "./globals.css";

import type { Metadata } from "next";
import { IBM_Plex_Serif } from "next/font/google";

const roboto = IBM_Plex_Serif({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
